### ISSUE TITLE
tf2_web_republisher

### ISSUE THREAD

**Issue by MerAARIZOU** [RobotWebTools/tf2_web_republisher#20]
I'm trying to study [tf2_web_republisher](https://github.com/RobotWebTools/tf2_web_republisher/blob/0df5347f12db858dc2f0031eab9f56cedbc1dd7f/src/tf_web_republisher.cpp) and I have some questions about the code. First of all, I didn't understand why in the actionserver constructor [line 117](https://github.com/RobotWebTools/tf2_web_republisher/blob/0df5347f12db858dc2f0031eab9f56cedbc1dd7f/src/tf_web_republisher.cpp#L117) has five parameters? I've reached the .h files and there is no such a constructor. 
The second question is about [the line 200](https://github.com/RobotWebTools/tf2_web_republisher/blob/0df5347f12db858dc2f0031eab9f56cedbc1dd7f/src/tf_web_republisher.cpp#L200) the setter must have a paramter acconrding to the .h file Any Clue? @T045T @rctoris 
Thank you
-Meriem

**Comment by T045T** [comment]
Hi Meriem,

The constructor you're talking about is [this one](http://docs.ros.org/jade/api/actionlib/html/classactionlib_1_1ActionServer.html#aefe7a407584e2a70beaacbdd3156c252) - see the typedef in [tf_web_republisher.cpp:60](https://github.com/RobotWebTools/tf2_web_republisher/blob/0df5347f12db858dc2f0031eab9f56cedbc1dd7f/src/tf_web_republisher.cpp#L60).

As for ```setAccepted()```, there's a default parameter for that, so there's no need to supply a value unless we wanted to add a message ([see the documentation for setAccepted()](http://docs.ros.org/jade/api/actionlib/html/classactionlib_1_1ServerGoalHandle.html#a045e0610d06f4da520460e0692af93c8)).

Lastly, while I'm happy to assist you in understanding the code, a Github issue isn't really the place for that. Issues are for bugs or improvements, http://answers.ros.org or plain Email are a better fit :)

Cheers,
Nils

**Comment by MerAARIZOU** [comment]
Thank you Nils. Actually I wasn't sure how to reach you, so I tried Github issues. Thank you for accepting to help me :)
