### ISSUE TITLE
Suggestion: Minimum publishing rate

### ISSUE THREAD

**Issue by jorgenfb** [RobotWebTools/tf2_web_republisher#32]
Use case:
I have a transform that stays stationary for longer periods when my robot stays in the same place. I want to limit messages in this case, but have a high rate of updates when it eventually starts moving. I can solve this by using `angularThres` and `transThres`. 

Next, I want to detect when this frame stops updating (and notify the user that the data can't be trusted anymore). This is not possible, since I can't distinguish between _no movement_ and _no tf updates_. 

My proposed solution to this would be to add a minimum publishing rate that would force the latest received frame to be published (or republished) if the stamp of the last published frame is older that the minimum threshold.

I'm happy to create a PR if this sounds useful. Any thoughts?

**Comment by MerAARIZOU** [comment]
I have worked on something similar. I wrote a package which can select only primary tf values and publish them to clients. I have noticed that even with no movement there are redundant tf updates. You can take a look on my package https://github.com/MerAARIZOU/py_tf2_web and the client side scripts that I modified https://github.com/MerAARIZOU/optimal_ros_lib_3d
