### ISSUE TITLE
Maintenance status update

### ISSUE THREAD

**Issue by defunctzombie** [RobotWebTools/tf2_web_republisher#34]
In a recent [ROS Webtools Group](https://github.com/RobotWebTools/community) ([meeting notes](https://docs.google.com/document/d/1esrRj2x80TSCEHOwuh-cT_bQvAqqvloQAQr8mPMzcTc/edit?usp=sharing)) we went through the various repositories and archived the ones that were obviously unmaintained or not strictly web specific.

This project wasn't obviously unmaintained but it also wasn't obviously maintained. It also wasn't exactly clear to us what is web specific about this project or how it fits into broader ROS web tooling.

Should the community consider this project maintained? Who's the active maintainer? Or should we mark the project as archived and direct folks to different approaches?

**Comment by amacneil** [comment]
If anyone is interested in maintaining this repository, please open an issue in https://github.com/RobotWebTools/community.

Otherwise, we will archive this repository after 2021-10-31.
